<?php
function rokuCats()
{
    echo "<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\n";
	echo "<!-- Generated by RoVidX Roku Addon (Basic) -->\n";
    $podShow    = get_option('rovidx_settings', 'ctitle');
    $podCat     = get_option('rovidx_settings', 'catslug');
    $podDesc    = get_option('rovidx_settings', 'cdesc');
    $noshows    = get_option('rovidx_settings', 'noofshow');
    $podThumbSD = get_option('rovidx_settings', 'cthumbsd');
    $podThumbHD = get_option('rovidx_settings', 'cthumbhd');
    $showno     = $noshows['noofshow'];
    $cout       = 0;
?>
<categories><?php
    while ($showno > 0) {
        $cout = $cout + 1;
		
?>
	<category title="<?php echo $podShow['ctitle' . $cout]; ?>" description="<?php echo $podDesc['cdesc' . $cout]; ?>" sd_img="<?php echo $podThumbSD['cthumbhd' . $cout]; ?>" hd_img="<?php echo $podThumbHD['cthumbhd' . $cout]; ?>">
		<categoryLeaf title="" description="<?php echo $podDesc['cdesc' . $cout]; ?>" feed="<?php echo get_site_url(); ?>/feed/roku-<?php echo $podCat['catslug' . $cout] . '/?key=' . $cout; ?>"/>
	</category>
	<?php
	echo '';
    $showno = ($showno - 1);
    }?></categories>
<?php
}
// Channel Functions

function rokuChannel()
{
    global $rovidx_options;
    echo "<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\n";
    echo "<!--Generated by RoVidX -->\n";
    $keyer            = $_GET['key'];
    $cater            = $rovidx_options['catslug' . $keyer];
    $qry              = new WP_Query('cat=' . $cater);
    $image_attributes = wp_get_attachment_image_src($attachment_id);
    $image            = wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'single-post-thumbnail');
?><feed>
<resultLength><?php
    if ($qry->have_posts()) {
        $category = $qry->get_queried_object();
        echo $category->category_count;
        ;
    }
?></resultLength>
<endIndex>20</endIndex>
<?php
    if ($qry->have_posts()) {
        while ($qry->have_posts()) {
            $qry->the_post();
?>	<item sdImg="<?php echo rovidx_featured_img_url('thumbnail'); ?>" hdImg="<?php echo rovidx_featured_img_url('thumbnail'); ?>">
		<title><?php $mykey_values = get_post_custom_values('rovidx_vtitle');
            foreach ($mykey_values as $key => $value) {
			$value = str_replace(array('<', '>', '{', '}', '*'), array(''), $value);
			$value = str_replace(array('&'), array('and'), $value); 
              echo "$value";
            }
?></title>
		<contentId><?php
            echo get_the_ID();
?></contentId>
		<contentType><?php
            $mykey_values = get_post_custom_values('rovidx_vtype');
            foreach ($mykey_values as $key => $value) {
                echo "$value";
				
            }
?></contentType>
		<contentQuality>SD</contentQuality>
		<releaseDate><?php
$release = get_the_date( 'm/d/y' );
echo $release;
?></releaseDate>
		<media>
			  <streamFormat>MP4</streamFormat>
			  <streamQuality>SD</streamQuality>
			  <streamBitrate><?php
            $mykey_values = get_post_custom_values('rovidx_vbitrate');
            foreach ($mykey_values as $key => $value) {
                echo "$value";
            }?></streamBitrate>
			  <streamUrl><?php
            $mykey_values = get_post_custom_values('rovidx_vurl');
            foreach ($mykey_values as $key => $value) {
                echo "$value";
            }
?></streamUrl>
		</media>
	<synopsis><?php
            $mykey_values = get_post_custom_values('rovidx_vdesc');
            foreach ($mykey_values as $key => $value) {
				$value = str_replace(array('<', '>', '{', '}', '*'), array(''), $value);
			$value = str_replace(array('&'), array('and'), $value); 
                echo "$value";
            }
?></synopsis>
	<genres><?php
            $mykey_values = get_post_custom_values('rovidx_vtype');
            foreach ($mykey_values as $key => $value) {
                echo "$value";
            }
?></genres>
	<runtime><?php
            $mykey_values = get_post_custom_values('rovidx_vlength');
            foreach ($mykey_values as $key => $value) {
                echo "$value";
            }
?></runtime>
</item>
<?php
        }
		echo "<!--RoVidX Powered Feed -->\n";
        echo "</feed>";
    }
}

function customXML()
{
    global $roFeed, $rovidx_options;
    $roDud   = $rovidx_options['noofshow'];
    $counter = $roDud;
    foreach ($roFeed['roplugin'] as $field) {
        $roMud = $field['name'];
        $roDee = $field['proc'];
        add_feed($roMud, $roDee);
    }
    while ($counter > 0) {
        $roBat   = 'catslug' . $counter;
        $roCat   = $rovidx_options[$roBat];
        $roDat   = 'roku-' . $roCat;
        $counter = $counter - 1;
        add_feed($roDat, 'rokuChannel');
    }
}
add_action('init', 'customXML');