<?php
// XML Categories Index Generator
$roOptions = get_option('rovidx_settings_roku');
function rokuBasicCats()
{
global $roOptions;
	
	$options = $roOptions;
	
	echo "<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\n";
	
	$userCat = $options["rokuCat"];
	?><categories><?php 
		foreach ($userCat as $catID) {
		
			$thisCat = get_category($catID, false);
			
			$imgCat = $thisCat->term_id;
			$imgURL = z_taxonomy_image_url($imgCat);
			$catName = $thisCat->name;
			$catName = str_replace(array('<', '>', '{', '}', '*'), array(''), $catName);
			$catName = str_replace(array('&'), array('and'), $catName);
			$catDesc = $thisCat->category_description;
			$catDesc = str_replace(array('<', '>', '{', '}', '*'), array(''), $catDesc);
			$catDesc = str_replace(array('&'), array('and'), $catDesc);
			$roBuilder = '<category title="' . $catName . '" description="' . $catDesc . '" sd_img="' . $imgURL . '" hd_img="' . $imgURL . '">';
			$subCats = get_categories(
			array(
			'orderby' => 'count',
			'order' => 'DESC',
			'child_of' => $catID,
			)
			);
			
			echo $roBuilder;
			foreach ($subCats as $Cats) {
					$catSID = $Cats->term_id;
					$catTit = $Cats->name;					
					$catTit = str_replace(array('<', '>', '{', '}', '*'), array(''), $catTit);
					$catTit = str_replace(array('&'), array('and'), $catTit);
					$catDes = $Cats->description;
					$catDes = str_replace(array('<', '>', '{', '}', '*'), array(''), $catDes);
					$catDes = str_replace(array('&'), array('and'), $catDes);
					$catURL = get_site_url().'/feed/roku/?key='.$catSID;
					$roSubBuilder = "\n<categoryLeaf title=\"".$catTit."\" description=\"\"  feed=\"".$catURL."\" />";
					echo $roSubBuilder;
				}
			$roBuilderClose = "</category>\n";
			echo $roBuilderClose;
			//return $roBuilder;
			}
		?></categories>
	<?php
}

//  Individual Category Builder

function rokuBasicChannel()
{
	$roOpt =  get_option('rovidx_settings_roku');
	$EpNoMax = $roOpt["noCat"];
    echo "<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\n";
    echo "<!--Generated by RoVidX Basic -->\n";

	$keyer          = $_GET['key'];
	$qry            = new WP_Query(array(
        								
											'posts_per_page' => $EpNoMax,
											'cat' => $keyer
											)
									);
    
echo $noPosts;
?><feed>
<resultLength><?php
    if ($qry->have_posts()) {
        $category = $qry->get_queried_object();
        echo $category->category_count;
        ;
    }
?></resultLength>
<endIndex><?php
    if ($qry->have_posts()) {
        $category = $qry->get_queried_object();
        $count = $category->category_count;
		$count = $count + 1;
		echo $count;
        ;
    }
?></endIndex><?php
    if ($qry->have_posts()) {
        while ($qry->have_posts()) {
            $qry->the_post();
			echo "\n";
?>
<item sdImg="<?php echo rovidx_featured_img_url('thumbnail'); ?>" hdImg="<?php echo rovidx_featured_img_url('medium'); ?>">
	<title><?php 
	$title = get_the_title();
	mb_convert_encoding($title, 'UTF-8', 'HTML-ENTITIES');
    $title = str_replace(array('&'), array(' and '), $title);
	echo $title;
?></title>
	<contentId><?php echo get_the_ID(); ?></contentId>
	<contentType><?php echo get_post_meta( get_the_id(),'rovidx_vtype', true); ?></contentType>
	<contentQuality><?php echo get_post_meta( get_the_id(),'rovidx_vformat',true); ?></contentQuality>
	<actor><?php  $mykey_values = get_post_meta( get_the_id(),'rovidx_vcast',true);
			echo $mykey_values;
  ?></actor>
	<director><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vdirector',true);
			echo $mykey_values;
			?></director>
	<releaseDate><?php
$release = get_the_date( 'm/d/y' );
echo $release;
?></releaseDate>
	<media>
		<streamFormat><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vform',true);
			echo $mykey_values;
			?></streamFormat>
		<streamQuality>SD</streamQuality>
		<streamBitrate><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vbitrate',true);
			echo $mykey_values; ?></streamBitrate>
		<streamUrl><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vurl',true);
            echo $mykey_values;
?></streamUrl>
	</media><?php
	$dunded = get_post_meta(get_the_id(),'rovidx_vformat',true);
	if ($dunded != 'SD') {
		echo "\n";
		?>
	<media>
		<streamFormat><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vform',true);
			echo $mykey_values;
		?></streamFormat>
		<streamQuality>HD</streamQuality>
		<streamBitrate><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vbitrate',true);
			echo $mykey_values;
			?></streamBitrate>
		<streamUrl><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vurlhd',true);
			echo $mykey_values;
			?></streamUrl>
	</media><?php
				}
				echo "\n";
?>
	<synopsis><?php
            $mykey_values = get_the_excerpt();
			$mykey_values = html_entity_decode($mykey_values);
            $mykey_values = str_replace(array("[…]","\n","\t","\r",'<', '>', '{', '}', '*'), array(''), $mykey_values);
            $mykey_values = str_replace(array('&'), array('and'), $mykey_values);
            echo $mykey_values;
			?></synopsis>
	<genres><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vtype',true);
			echo $mykey_values;?></genres>
	<runtime><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vlength',true);
			echo $mykey_values;?></runtime>
	<starrating><?php
            $mykey_values = get_post_meta(get_the_id(),'rating',true);
			if (empty($mykey_values)) {
				echo "0";
			}
           echo $mykey_values;
         
?></starrating>
<rating><?php
            $mykey_values = get_post_meta(get_the_id(),'rovidx_vrating',true);
			if ($mykey_values != NULL) {
            echo $mykey_values;
			} else {
				echo "NR";
			}
?></rating>
</item><?php
}
echo "</feed>";
}}
